### ISSUE TITLE
FastCopy installer crashes when using /EXTRACT64 command line option

### ISSUE THREAD

**Issue by Earthnuker** [FastCopyLab/FastCopy#18]
**Describe the bug**
When running the installer with `FastCopy4.0.2_installer.exe /EXTRACT64` it crashes:
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000409 (STATUS_STACK_BUFFER_OVERRUN)
          ExceptionFlags: 00000001
        ExceptionAddress: 0043D481 fastcopy4.0.2_installer.0043D481
        NumberParameters: 1
ExceptionInformation[00]: 00000005
Last chance exception on 0043D481 (C0000409, STATUS_STACK_BUFFER_OVERRUN)!
```
Using the "Extract only" button in the installer GUI works

**To Reproduce**
Run `FastCopy4.0.2_installer.exe /EXTRACT64`

**Command line options and various settings**
N/A

**Version/Environment**
 - FastCopy ver (principle, latest ver) :4.0.2
 - OS ver: Windows 10 20H2 (Build: 19042.1466)
